environment: ${ENVIRONMENT:-dev}
sentryDsn: ${SENTRY_DSN:-}

logging:
  appenders:
    - type: console
      layout:
        type: json

server:
  enableVirtualThreads: true
  requestLog:
    appenders:
      - type: console
        layout:
          type: access-json