environment: ${ENVIRONMENT:-dev}
sentryDsn: ${SENTRY_DSN:-}
applicationName: dropwizard-template

pyroscopeUrl: ${PYROSCOPE_URL}
pyroscopeUser: ${PYROSCOPE_USER}
pyroscopePass: ${PYROSCOPE_PASS}

swagger:
  resourcePackage: com.companyname.template.resources

logging:
  appenders:
    - type: console
      layout:
        type: json

server:
  enableVirtualThreads: true
  requestLog:
    appenders:
      - type: console
        layout:
          type: access-json

#metrics:
#  reporters:
#    - type: graphite
#      host: ${GRAPHITE_URL:-}
#      port: 443
#      prefix: dropwizard_template
#      transport: tcp